name: do something when branch is deleted

on:
  delete:
    branches:
      - 'delete_hook/**'
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          echo ${{ github.event.ref }}
          #        if: contains(github.event.ref, 'test/*')

